name: validate
on:
- push
- pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.noden }}
    - run: make validate.ci
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
